spring.application.name=byld-portfolio-api

server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/byld_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration